### **What is Numpy?**

- Numpy is the fundamental package for scientific computing in Python.
- It is a Python library that provides a multidimensional array object, various derived objects(such as masked array and matrices).
- Also an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting,slecting, I/O, descrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
- At the core of the NumPy package, is the ndarry object. This encapsulation n-dimensional arrays of homogenous data types.

### **Numpy Arrays vs Python Sequences**

- Numpy arrays have a fixed size at creation, unlike Python list(which can grow dynamically). Changing the size of an ndarray will create a new aray and delete the original.
- The elements in a NumPy array are required to be of the same data type, and thus will be the same size in memeory.
- NumPy arrays facillitate advanced mathematical and other types of operations on large numbers of data. Typically such operations are executed more efficently and with less code that is possible using Python's built-in sequences.
- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; through these typically support Python-sqeuence input, they convert such input to NumPy arrays propr to processing, and they often output NumPy arrays.


### **Create Numpy Array**


In [1]:
# importing required library
import numpy as np

In [2]:
# create Numpy array as scaler
scl = np.array(1)
print(scl)

# check type of array
print(type(scl))

# check dimension of array
print("dimension of array: ", scl.ndim)

# check shapeof array
print("shape of array:", scl.shape)

1
<class 'numpy.ndarray'>
dimension of array:  0
shape of array: ()


In [3]:
# create a numpy array as vector
vec = np.array([1, 2])
print(vec)
# check type of array
print("class of array: ", type(vec))

# checking dimension of array
print("dimension of array: ", vec.ndim)

# check shape of array
print("shape of array: ", vec.shape)

[1 2]
class of array:  <class 'numpy.ndarray'>
dimension of array:  1
shape of array:  (2,)


In [4]:
# Numpy 2D array as matric
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat)
# check type of array
print("class of array: ", type(mat))

# checking dimension of array
print("Dimension of array: ", mat.ndim)

# check shape of array
print("shape of array: ", mat.shape)

[[1 2 3]
 [4 5 6]]
class of array:  <class 'numpy.ndarray'>
Dimension of array:  2
shape of array:  (2, 3)


In [5]:
# Naumpy 3d array as tensor
ten = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(ten)

# check type of array
print("class of array: ", type(ten))

# checking dimension of array
print("Dimensionof array: ", ten.ndim)

# check shape of array
print("shape of array: ", ten.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
class of array:  <class 'numpy.ndarray'>
Dimensionof array:  3
shape of array:  (1, 3, 3)


### **Check and Change data type of array**


In [6]:
# check data type of aray
print(ten.dtype)

int32


In [7]:
# change data type of array
ten_16 = ten.astype("float16")
print(ten_16)
print(ten_16.dtype)

[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]
float16


In [8]:
ten_int16 = ten.astype("int16")
print(ten_16)
print(ten_int16.dtype)

[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]
int16


In [9]:
ten_bool = ten.astype("bool")
print(ten_bool)
print(ten_bool.dtype)

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
bool


### **np.arange**

- Return evenly spaced values within a given interval.
- arange can be called with a varying number of positional arguments.

- **syntax**:

  - np.arange(stop): values are generated within the half-open inerval[0, stop].
  - np.arange(start, stop): values are generated within the half-open interval[start, stop].
  - np.arange(start, stop, step): values are generated within the half-open interval[start, stop], with spacing between values given by step.

- **parameters**:

  - **start**:integer/real, Start of interval. The interval includes this value. The default start value is 0.

  - **stop**: integer/real,End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.

  - **step**: integer/real, Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The default step size is 1. If step is specified as a position argument, start must also be given.

  - **dtype**: dtype,optional, The type of the output array. If dtype is not given, infer the data type from the other input arguments.

  - **like**: array_like, optional, Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the \***\* array_function \*\*** protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.


In [10]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
arr_ss = np.arange(1, 10)
print(arr_ss)

[1 2 3 4 5 6 7 8 9]


In [12]:
arr_sss = np.arange(1, 10, 2)
print(arr_sss)

[1 3 5 7 9]


### **numpy.reshape**

- **np.reshape()**: gives a new shape to an array without changing its data.
- **Syntax: np.reshape(a, newshape, order)**
- **Parameters:**
  - **a**: array to be reshaped.
  - **newshape**: The new shape should be compatible with the original shape. If an integer, then the result will be a 1-D array of that length. One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.
  - **Order:**
    - **C:** means to read / write the elements using C-like index order, with the last axis index changing fastest, back to the first axis index changing slowest.
    - **F:** means to read / write the elements using Fortran-like index order, with the first index changing fastest, and the last index changing slowest.
    - **A:** means to read / write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise.


In [13]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [14]:
a = np.reshape(a, (3, 4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### **numpy.ones**

- Return a new array of given shape and type, filled with ones.
- **syntax**: numpy.ones(shape, dtype=None, order='c',\*, Like=None)
- **Parameters**:
  - **shape**: int/sequence of ints, Shape of the new array, e.g., (2, 3) or 2.
  - **dtype**: data-type/opetional, The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.
  - **order**: {C, F}/opetional, default:C, Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.
  - **Like**: array_like/optional, Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the \_\_ **array_function** \_\_ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.


In [15]:
# create a np.ones
one = np.ones((3, 4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
b = np.ones((5, 6), dtype=np.int16)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### **numpy.random.random**

**random.random(size=None)**: Return random floats in the half-open interval [0.0, 1.0). Alias for random_sample to ease forward-porting to the new random API.


In [17]:
ran = np.random.random((3, 4))
print(ran)

[[0.27139715 0.68873031 0.84842861 0.91685186]
 [0.99836718 0.79720431 0.35882148 0.11035553]
 [0.5770997  0.462053   0.84846595 0.80794079]]


### **numpy.linspace**:

- Return evenly spaced numbers over a specified interval.
- Returns num evenly spaced samples, calculated over the interval [start, stop].
- The endpoint of the interval can optionally be excluded.
- **Syntax**

  - **numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)**

- **Paramters**

  - **star**:(array_like), The starting value of the sequence.

  - **stop**:(array_like), The end value of the sequence, unless endpoint is set to False. In that case, the sequence consists of all but the last of num + 1 evenly spaced samples, so that stop is excluded. Note that the step size changes when endpoint is False.

  - **num**:(int/optional)->Number of samples to generate. Default is 50. Must be non-negative.

  - **endpoint**:(bool/optional),If True, stop is the last sample. Otherwise, it is not included. Default is True.

  - **retstep**:(bool, optional),If True, return (samples, step), where step is the spacing between samples.

  - **dtype**:(dtype, optional),The type of the output array. If dtype is not given, the data type is inferred from start and stop. The inferred dtype will never be an integer; float is chosen even if the arguments would produce an array of integers.

  - **axis**:(int/optional) The axis in the result to store the samples. Relevant only if start or stop are array-like. By default (0), the samples will be along a new axis inserted at the beginning. Use -1 to get an axis at the end.


In [18]:
ln = np.linspace(2, 3, num=5)
print(ln)

[2.   2.25 2.5  2.75 3.  ]


### **numpy.identity** :

- Return the identity array
- The identity array is a square array with ones on the main diagonal.
- **Syntax**
  numpy.identity(n, dtype=None, \*, like=None)

- **Parameters**:

  - **n**:(int),Number of rows (and columns) in n x n output.

  - **dtype**:(data-type, optional),Data-type of the output. Defaults to float.

  - **like**:(array_like, optional): Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the \_\_ **array_function** \_\_ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.


In [19]:
idd = np.identity(3)
print(idd)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### **Array Attributes**


### **Changing DataType**


In [20]:
ran.astype(np.int32)
print(ran)

[[0.27139715 0.68873031 0.84842861 0.91685186]
 [0.99836718 0.79720431 0.35882148 0.11035553]
 [0.5770997  0.462053   0.84846595 0.80794079]]


### **Array Operations**


In [21]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
# Scaler Operations

# arithmetic
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [23]:
# relational operators
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [24]:
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [25]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [26]:
# vectors operations
a3 = a1 + a2
a3

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### **Array Functions**


In [27]:
a1 = np.random.random((3, 3))
a1 = np.round(a1 * 100)
a1

array([[98., 84.,  3.],
       [34., 95., 96.],
       [46., 82., 42.]])

In [28]:
# max/min/sum/prod
np.max(a1)

98.0

In [29]:
np.min(a1)

3.0

In [30]:
np.sum(a1)

580.0

In [31]:
np.prod(a1)

1213169117368320.0

In [33]:
# find minimum of each row column -> 0, row -> 1
np.min(a1, axis=0)

array([34., 82.,  3.])

In [35]:
np.max(a1, axis=1)

array([98., 96., 82.])

In [37]:
# mean/median/std/var
meen = np.mean(a1)
print("meen=", meen)

med = np.median(a1)
print("med=", med)

stdr = np.std(a1)
print("standard_deviation =", stdr)

var = np.var(a1)
print("varaiance=", var)

meen= 64.44444444444444
med= 82.0
standard_deviation = 32.132057758607196
varaiance= 1032.469135802469


### **Trigonometric functions**


In [38]:
np.sin(a1)

array([[-0.57338187,  0.73319032,  0.14112001],
       [ 0.52908269,  0.68326171,  0.98358775],
       [ 0.90178835,  0.31322878, -0.91652155]])

### **Dot Product**


In [44]:
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(12, 24).reshape(4, 3)

np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

### **Log & Exponents**


In [45]:
np.log(a1)

array([[4.58496748, 4.4308168 , 1.09861229],
       [3.52636052, 4.55387689, 4.56434819],
       [3.8286414 , 4.40671925, 3.73766962]])

In [46]:
np.exp(a1)

array([[3.63797095e+42, 3.02507732e+36, 2.00855369e+01],
       [5.83461743e+14, 1.81123908e+41, 4.92345829e+41],
       [9.49611942e+19, 4.09399696e+35, 1.73927494e+18]])

### **Round/floor/ceil**


In [47]:
np.round(np.random.random((2, 3)) * 100)

array([[55., 48., 81.],
       [97., 98., 77.]])

In [48]:
np.floor(np.random.random((2, 3)) * 100)

array([[90., 71., 87.],
       [26., 40., 92.]])

In [49]:
np.ceil(np.random.random((2, 3)) * 100)

array([[93., 68., 75.],
       [37., 48., 16.]])