### **What is Numpy?**

- Numpy is the fundamental package for scientific computing in Python.
- It is a Python library that provides a multidimensional array object, various derived objects(such as masked array and matrices).
- Also an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting,slecting, I/O, descrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
- At the core of the NumPy package, is the ndarry object. This encapsulation n-dimensional arrays of homogenous data types.

### **Numpy Arrays vs Python Sequences**

- Numpy arrays have a fixed size at creation, unlike Python list(which can grow dynamically). Changing the size of an ndarray will create a new aray and delete the original.
- The elements in a NumPy array are required to be of the same data type, and thus will be the same size in memeory.
- NumPy arrays facillitate advanced mathematical and other types of operations on large numbers of data. Typically such operations are executed more efficently and with less code that is possible using Python's built-in sequences.
- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; through these typically support Python-sqeuence input, they convert such input to NumPy arrays propr to processing, and they often output NumPy arrays.


### **Create Numpy Array**


In [2]:
#importing required library
import numpy as np

In [9]:
#create Numpy array as scaler
scl = np.array(1)
print(scl)

#check type of array
print(type(scl))

#check dimension of array
print("dimension of array: ",scl.ndim)

#check shapeof array
print("shape of array:",scl.shape)

1
<class 'numpy.ndarray'>
dimension of array:  0
shape of array: ()


In [12]:
#create a numpy array as vector
vec = np.array([1,2])
print(vec)
#check type of array
print("class of array: ",type(vec))

#checking dimension of array
print("dimension of array: ",vec.ndim)

#check shape of array
print("shape of array: ",vec.shape)

[1 2]
class of array:  <class 'numpy.ndarray'>
dimension of array:  1
shape of array:  (2,)


In [13]:
#Numpy 2D array as matric
mat = np.array([[1,2,3],[4,5,6]])
print(mat)
#check type of array
print("class of array: ",type(mat))

#checking dimension of array
print("Dimension of array: ", mat.ndim)

#check shape of array
print("shape of array: ",mat.shape)

[[1 2 3]
 [4 5 6]]
class of array:  <class 'numpy.ndarray'>
Dimension of array:  2
shape of array:  (2, 3)


In [15]:
#Naumpy 3d array as tensor
ten = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(ten)

#check type of array
print("class of array: ",type(ten))

#checking dimension of array
print("Dimensionof array: ",ten.ndim)

#check shape of array
print("shape of array: ",ten.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
class of array:  <class 'numpy.ndarray'>
Dimensionof array:  3
shape of array:  (1, 3, 3)


### **Check and Change data type of array**


In [16]:
#check data type of aray
print(ten.dtype)

int32


In [24]:
#change data type of array
ten_16 = ten.astype('float16')
print(ten_16)
print(ten_16.dtype)

[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]
float16


In [26]:
ten_int16 = ten.astype('int16')
print(ten_16)
print(ten_int16.dtype)

[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]
int16


In [28]:
ten_bool = ten.astype('bool')
print(ten_bool)
print(ten_bool.dtype)

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
bool


### **np.arange**

- Return evenly spaced values within a given interval.
- arange can be called with a varying number of positional arguments.

- **syntax**:

  - np.arange(stop): values are generated within the half-open inerval[0, stop].
  - np.arange(start, stop): values are generated within the half-open interval[start, stop].
  - np.arange(start, stop, step): values are generated within the half-open interval[start, stop], with spacing between values given by step.

- **parameters**:

  - **start**:integer/real, Start of interval. The interval includes this value. The default start value is 0.

  - **stop**: integer/real,End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.

  - **step**: integer/real, Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The default step size is 1. If step is specified as a position argument, start must also be given.

  - **dtype**: dtype,optional, The type of the output array. If dtype is not given, infer the data type from the other input arguments.

  - **like**: array_like, optional, Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the \***\* array_function \*\*** protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.


In [30]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
arr_ss =np.arange(1,10)
print(arr_ss)

[1 2 3 4 5 6 7 8 9]


In [32]:
arr_sss = np.arange(1,10,2)
print(arr_sss)

[1 3 5 7 9]
